### PR TITLE
Calculator App

### PR DESCRIPTION
**Pull request by saimaAnis21**
In this project we did:
1-Setup the project for Calculator App
2-Install dependencies such as Big.js and prop-types
3-Deploy app to Heroku

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @saimaAnis21**

Great job with the project so far it looks amazing. the app is created with create-react-app and the required packages are added. but, there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] Please make sure to fix all of the linters errors.
- [ ] Please make sure to delete any unnecessary files.

 
---


please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @saimaAnis21, great job on this milestone :+1: Nice job removing all the unnecessary files :+1: However, let us kindly address the following comments below:

- Kindly create a .gitignore file and reference the noode_modules path. This is why the file change is 5000+ and it slows the application
- Kindly fix the stylelint errors we are currently having **Hint**: Create a CSS file

Once these are addressed, kindly submit another code review request :smile: 
_Happy coding_ :woman_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by saimaAnis21** [comment]
> ## Status: Require changes  
> Hi @saimaAnis21, great job on this milestone  Nice job removing all the unnecessary files  However, let us kindly address the following comments below:
> 
> * Kindly create a .gitignore file and reference the noode_modules path. This is why the file change is 5000+ and it slows the application
> * Kindly fix the stylelint errors we are currently having **Hint**: Create a CSS file
> 
> Once these are addressed, kindly submit another code review request 
> _Happy coding_ 
> [Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

Hi, @addod19  I have fixed the node modules issue, however, I'm having difficulty fixing the stylelint error. Can you kindly guide me on how to fix the issue

**Review by addod19 — APPROVED** [review]
## Status: Approved : 🏆🎈 

Hi @saimaAnis21, congratulations on this milestone 👍 The node_modules have been added to the gitignore file 😄 The styelint errors have also been addressed 👍 Awesome job

I hereby approved the project, kindly go ahead and merge into development. Do not forget to submit the project completion form
_Happy coding_ 👩‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/mwlite/in/daniel-larbi-addo)

**Pull request merged**
